
language: node_js

node_js:
  - 8
  - 9

cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries
    - $HOME/node_modules
    - node_modules

before_script:
  - chmod -R +x sh

before_install:
  - node sh/install-peers.js
